---
output: pdf_document
---

# Determining the Price of San Francisco AirBnB Listings
#### The Outliers: Hailey han, Joshua Minwoo Kang, Jihong Lee

``` {r, warning=FALSE}
#### Initial Setup

# read in dataset
setwd("/Users/jihonglee/Dropbox/Spring-2020/STAT 346/Final Project")
listings <- read.csv("listings.csv")
dim(listings)

# choose subset with variables of interest
listings <- subset(listings, select=c("price", "host_response_rate", "host_is_superhost", "neighbourhood", 
                                      "latitude", "longitude", "property_type", "room_type", "accommodates", 
                                      "bathrooms", "bedrooms", "number_of_reviews", "review_scores_rating"))

# organize into variables for later ease
listings$price <- as.numeric(gsub("[$]", "", listings$price))
listings$host_response_rate <- as.numeric(gsub("[%]", "", listings$host_response_rate))

# clean of invalid observations
listings <- listings[complete.cases(listings), ]
dim(listings)

#### Exploratory Data Analysis

# quantitative variables in dataset: price, host response rate, latitude, longitude, accommodates, bathrooms, bedrooms, number of reviews, review_scores_rating
listings_quant <- subset(listings, select=c("price", "host_response_rate", "latitude", "longitude", "accommodates",
                                            "bathrooms", "bedrooms", "number_of_reviews", "review_scores_rating"))
# categorical variables in dataset: host is superhost, neighborhood, property type, room type
listings_cat <- subset(listings, select=c("host_is_superhost", "neighbourhood", "property_type", "room_type"))

## Univariate EDA

# statistical display of quantitative variables
l_mean <- apply(listings_quant, 2, mean)
l_sd <- apply(listings_quant, 2, sd)
l_med <- apply(listings_quant, 2, median)
l_iqr <- apply(listings_quant, 2, IQR, na.rm=T)
l_min <- apply(listings_quant, 2, min)
l_max <- apply(listings_quant, 2, max)

statsum <- data.frame(l_mean, l_sd, l_med, l_iqr, l_min, l_max)
rownames(statsum) <- c('Price ($)', 'Host Response Rate (%)', 'Latitude', 'Longitude', 'Number of People Accommodated', 'Number of Bathrooms', 'Number of Bedrooms', 'Number of Reviews', 'Overall Rating')
colnames(statsum) <- c("Mean", "Standard Deviation", "Median", "IQR", "Minimum", "Maximum")
statsum
```

``` {r, fig.width=12, fig.height=10}
# graphical display of quantitative variables
par(mfrow=c(3,3))
quantvars <- with(listings, cbind(price, host_response_rate, latitude, longitude, accommodates, bathrooms, bedrooms, number_of_reviews, review_scores_rating)); quantnum <- 9
quantnames <- c('Price ($)', 'Host Response Rate (%)', 'Latitude', 'Longitude', 'Number of People Accommodated', 'Number of Bathrooms', 'Number of Bedrooms', 'Number of Reviews', 'Overall Rating')
for(i in 1:quantnum) {
  hist(quantvars[, i], main="",
       xlab=quantnames[i], ylab="Frequency",
       breaks=30, col="#3C787E")
}
```

``` {r}
# statistical display of categorical variables
superhost_tab <- table(listings$host_is_superhost)
neighborhood_tab <- table(listings$neighbourhood)
property_tab <- table(listings$property_type)
room_tab <- table(listings$room_type)

superhost_tab
neighborhood_tab
property_tab
room_tab
```

``` {r, fig.width=12, fig.height=10, out.width='80%', fig.align="center"}
# graphical display of categorical variables
par(mfrow=c(2,2))
barplot(superhost_tab, main="",
          xlab="Superhost", ylab="Frequency",
          col="#3C787E")
barplot(neighborhood_tab, main="",
          xlab="Neighborhood", ylab="Frequency",
          col="#3C787E")
barplot(property_tab, main="",
          xlab="Property Type", ylab="Frequency",
          col="#3C787E")
barplot(room_tab, main="",
          xlab="Room Type", ylab="Frequency",
          col="#3C787E")
```

``` {r, fig.width=20, fig.height=18}
## Multivariate EDA

# define panel.cor function to use as personalized pairs plot
panel.cor <- function(x, y, digits=2, prefix="", cex.cor) {
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  r <- cor(x, y)
  txt <- format(c(r, 0.123456789), digits=digits)[1]
  txt <- paste(prefix, txt, sep="")
  if(missing(cex.cor)) cex <- 2
  test <- cor.test(x, y)
  signif <- symnum(test$p.value, corr=FALSE, na=FALSE,
                   cutpoints = c(0, 0.001, 0.01, 0.05, 0.1, 1),
                   symbols = c("***", "**", "*", ".", " "))
  text(0.5, 0.5, txt, cex=cex)
  text(0.8, 0.8, signif, cex=cex, col=2)
}

# relationship between quantitative variables
pairs(listings_quant, lower.panel=panel.cor)
```

``` {r, fig.width=20, fig.height=18}
# relationship between categorical variables
par(mfrow=c(2,2))
catvars <- with(listings, cbind(host_is_superhost, neighbourhood, property_type, room_type)); catnum <- 4
catnames <- c('Superhost', 'Neighborhood', 'Property Type', 'Room Type')
for(i in 1:catnum) {
  boxplot(listings$price ~ catvars[, i], main="",
          ylab="Price of AirBnB Listing ($)",
          xlab=catnames[i])
}
```


